### ISSUE TITLE
Compatibility with Airports DLC

### ISSUE THREAD

**Issue by gcwtai** [sidseth26/MoreVehiclesOffline#2]
Would you edit this mod so that it is compatible with Airports DLC?

**Comment by cohdir** [comment]
How do u make all the source files into mod? apparently I managed to get it offline by changing sum of its source codes

**Comment by MyNameIsBorat** [comment]
i just went through the source code to remove anything that connected to network. Then read official documentation to compile.

**Comment by MyNameIsBorat** [comment]
You need vs studio 2019 for this

**Comment by MyNameIsBorat** [comment]
You need vs studio 2019 for this

**Comment by cohdir** [comment]
Which documentation? and yeah I use the newest VS Studio. Since you're here would you update this mod?😁

**Comment by MyNameIsBorat** [comment]
https://github.com/dymanoid/MoreVehicles

**Comment by MyNameIsBorat** [comment]
this is the official repository. my memory is unfortunately blank on how i did it. i just remember that it toom me 2 days to figure out what i had to change. then another day to learn how vscode works. i vaguely remember that you had to go to solution explorer to select and compile this mod. check c:s wiki on compiling mods

**Comment by cohdir** [comment]
I keep getting error at MoreVehicles.csproj

`[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\My_PC\AppData\Local\Colossal Order\Cities_Skylines\Addons\Mods\MoreVehicles-1.1.3\src\MoreVehicles\MoreVehicles.csproj`

It's that thing started with `<Project SDK="Microsoft.net.Sdk">`

**Comment by MyNameIsBorat** [comment]
Just follow the documentation is the best advice i can give you. This was my first and last time i worked on vs studio. I struggled with errors as well. But they would most likely be due to missing imports of dll or some settings. Just recheck everything.

**Comment by cohdir** [comment]
Hey man, I know its been months and I've seen some progress on this mod build up, I managed to disable the Steam workshop activation and deal with most of the coding problems. However there is this GitVersionTask thing that until today I don't have any clue on how to fix it..

_error : DirectoryNotFoundException: Can't find the .git directory in_...

It shows me the problem is in this line of code

```
<GenerateGitVersionInformation SolutionDirectory="$(GitVersionPath)"
                                       ConfigFilePath="$(GitVersionConfig)"
                                       NoFetch="$(GitVersion_NoFetchEnabled)"
                                       NoNormalize="$(GitVersion_NoNormalizeEnabled)"
                                       ProjectFile="$(MSBuildProjectFullPath)"
                                       IntermediateOutputPath="$(IntermediateOutputPath)"
                                       Language="$(Language)">
```
I know youve lost memories on how you build this mod but you got any ideas to deal with this Git problem?
Thanks

**Comment by MyNameIsBorat** [comment]
Hi, will you be able to connect via zoom? We will figure it out once and for all

**Comment by cohdir** [comment]
Riggght on brother you got Discord? we can talk more on it if you dont mind🙏

**Comment by cohdir** [comment]
I noticed that your source code got lotsa differences from the original source code, especially yours seem aint having those Git bullshits. Did you make it from scratch?

**Comment by MyNameIsBorat** [comment]
Sent you a request on discord
