### ISSUE TITLE
Mod Update Request

### ISSUE THREAD

**Issue by Richardinho1** [sidseth26/MoreVehiclesOffline#3]
Can this offline mod be updated to match the latest version which fixes a critical bug regarding airports dlc

**Comment by MyNameIsBorat** [comment]
I don't have the game anymore. Pls feel free to try and copy the master of original mod and recompile it using cs tutorial

**Comment by Glitcher3000** [comment]
What and where is this "cs tutorial"? I'm not a modder and don't believe I'm up to the task. Is there any way to get a working version of this offline mod for Cities Skylines 1.17.1-f4?
